services:
  # ──────────────────────────────
  backend:
    build: ./backend
    volumes:
      - ./backend:/app            # hot-reload para Flask
    environment:
      - FLASK_APP=app.py
      - MONGO_URI=mongodb://mongo:27017/sophia_db
    command: flask run --host=0.0.0.0 --port=5000 --reload
    depends_on:
      - mongo
    restart: unless-stopped

  # ──────────────────────────────
  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  # ──────────────────────────────
  frontend-dev:                   # NEW: Development frontend with hot-reload
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev   # Create this file
    ports:
      - "3000:3000"               # React dev server port
    volumes:
      - ./frontend/src:/app/src    # Mount source code for hot-reload
      - ./frontend/public:/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable file watching in Docker
    depends_on:
      - backend
    restart: unless-stopped

  # ──────────────────────────────
  web:                            # Production frontend (+ Nginx)
    build: ./frontend             
    ports:
      - "80:80"                   
    depends_on:
      - backend
    restart: unless-stopped
    profiles:
      - production                # Only run in production profile

volumes:
  mongo-data:
