services:
  # ──────────────────────────────
  backend:
    build: ./backend
    volumes:
      - ./backend:/app            # hot-reload para Flask
    environment:
      - FLASK_APP=app.py
    command: flask run --host=0.0.0.0 --port=5000 --reload
    depends_on:
      - mongo
    restart: unless-stopped

  # ──────────────────────────────
  mongo:
    image: mongo:7.0
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  # ──────────────────────────────
  web:                            # frontend (+ Nginx) multietapa
    build: ./frontend             # usa el Dockerfile con HtmlWebpackPlugin
    ports:
      - "80:80"                   # localhost → contenedor:80
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo-data:
